
GET http://localhost:8080/aa/game/create/?seed=12345

> {% client.global.set("gameid", response.body); %}

###
GET http://localhost:8080/bot-west/game/join/{{gameid}}
###
GET http://localhost:8080/yy/game/join/{{gameid}}
###
GET http://localhost:8080/bot-east/game/join/{{gameid}}

###
GET http://localhost:8080/aa/state

###
GET http://localhost:8080/yy/state


###
GET http://localhost:8080:/ui/game-view.html
# http://192.168.1.85:8080/ui/game-view.html?gameId=e1a4104a-4594-4fd9-a9a9-174605392ec5&player=yy